/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ControleFuncionario;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
/**
 *
 * @author pedromoreira
 */
public class CadastroFuncionario extends javax.swing.JDialog {

    ControleFuncionario controleFuncionario = new ControleFuncionario();
    TelaPrincipal telaPrincipal;

    public CadastroFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
        public CadastroFuncionario (TelaPrincipal telaPrincipal, boolean modal, ControleFuncionario controleFuncionario) {
        super();  // Chamando o construtor da superclasse JFrame
        this.controleFuncionario = controleFuncionario;  // Inicializando o controle de produto
        this.telaPrincipal = telaPrincipal;  // Referência à tela principal, se necessário
        initComponents();  // Inicializando componentes da GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JL_textoPrincipal = new javax.swing.JLabel();
        JB_cadastrar1 = new javax.swing.JButton();
        JB_limpar = new javax.swing.JButton();
        JB_cancelar = new javax.swing.JButton();
        JTF_nome = new javax.swing.JTextField();
        JTF_cpf = new javax.swing.JTextField();
        JTF_salario = new javax.swing.JTextField();
        JL_nome = new javax.swing.JLabel();
        JL_cpf = new javax.swing.JLabel();
        JL_salario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JL_textoPrincipal.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        JL_textoPrincipal.setText("Cadastrar Funcionário");

        JB_cadastrar1.setText("Cadastrar");
        JB_cadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_cadastrar1ActionPerformed(evt);
            }
        });

        JB_limpar.setText("Limpar");
        JB_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_limparActionPerformed(evt);
            }
        });

        JB_cancelar.setText("Cancelar");
        JB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_cancelarActionPerformed(evt);
            }
        });

        JL_nome.setText("Nome:");

        JL_cpf.setText("CPF:");

        JL_salario.setText("Salário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JL_nome)
                    .addComponent(JL_salario)
                    .addComponent(JL_cpf))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_textoPrincipal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_cadastrar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_cancelar))
                    .addComponent(JTF_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(JL_textoPrincipal)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_nome))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_cpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_salario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_cadastrar1)
                    .addComponent(JB_limpar)
                    .addComponent(JB_cancelar))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_cadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_cadastrar1ActionPerformed
        String nome = this.JTF_nome.getText(); 
        String cpf = this.JTF_cpf.getText();  
        String salarioText = this.JTF_salario.getText();  

        // Verificando se os campos estão vazios
        if (nome.isEmpty() || cpf.isEmpty() || salarioText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, preencha todos os campos!", "Erro de Cadastro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double salario = Double.parseDouble(salarioText);  // Convertendo o texto de quantidade para double

            // Chamando o método de cadastro do controle de produto
            boolean funcionarioCadastrado = controleFuncionario.cadastrarFuncionario(nome, cpf, salario);

            if (funcionarioCadastrado) {
                JOptionPane.showMessageDialog(rootPane, "Funcionário cadastrado com sucesso!", "Cadastro de Funcionário", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Funcionário com o código " + cpf + " já existe!", "Erro de Cadastro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Tratando caso a conversão para double falhe
            JOptionPane.showMessageDialog(rootPane, "Por favor, insira um número válido para o salário.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JB_cadastrar1ActionPerformed

    private void JB_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_limparActionPerformed
        this.JTF_nome.setText(null);
        this.JTF_cpf.setText(null);
        this.JTF_salario.setText(null);
    }//GEN-LAST:event_JB_limparActionPerformed

    private void JB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JB_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroFuncionario dialog = new CadastroFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_cadastrar1;
    private javax.swing.JButton JB_cancelar;
    private javax.swing.JButton JB_limpar;
    private javax.swing.JLabel JL_cpf;
    private javax.swing.JLabel JL_nome;
    private javax.swing.JLabel JL_salario;
    private javax.swing.JLabel JL_textoPrincipal;
    private javax.swing.JTextField JTF_cpf;
    private javax.swing.JTextField JTF_nome;
    private javax.swing.JTextField JTF_salario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
