/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ControleProduto;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

public class CadastroProduto extends javax.swing.JDialog {

    ControleProduto controleProduto = new ControleProduto();
    TelaPrincipal telaPrincipal;
    
    public CadastroProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public CadastroProduto (TelaPrincipal telaPrincipal, boolean modal, ControleProduto controleProduto) {
        super();  // Chamando o construtor da superclasse JFrame
        this.controleProduto = controleProduto;  // Inicializando o controle de produto
        this.telaPrincipal = telaPrincipal;  // Referência à tela principal, se necessário
        initComponents();  // Inicializando componentes da GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JB_cancelar = new javax.swing.JButton();
        JTF_nome = new javax.swing.JTextField();
        JTF_codigo = new javax.swing.JTextField();
        JTF_quantidade = new javax.swing.JTextField();
        JL_nome = new javax.swing.JLabel();
        JL_codigo = new javax.swing.JLabel();
        JL_quantidade = new javax.swing.JLabel();
        JL_textoPrincipal = new javax.swing.JLabel();
        JB_cadastrar = new javax.swing.JButton();
        JB_limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JB_cancelar.setText("Cancelar");
        JB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_cancelarActionPerformed(evt);
            }
        });

        JL_nome.setText("Nome:");

        JL_codigo.setText("Código:");

        JL_quantidade.setText("Quantidade:");

        JL_textoPrincipal.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        JL_textoPrincipal.setText("Cadastrar Produto");

        JB_cadastrar.setText("Cadastrar");
        JB_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_cadastrarActionPerformed(evt);
            }
        });

        JB_limpar.setText("Limpar");
        JB_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JL_nome)
                    .addComponent(JL_quantidade)
                    .addComponent(JL_codigo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_cancelar))
                    .addComponent(JL_textoPrincipal)
                    .addComponent(JTF_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(JL_textoPrincipal)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_nome))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_quantidade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_cadastrar)
                    .addComponent(JB_limpar)
                    .addComponent(JB_cancelar))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JB_cancelarActionPerformed

    private void JB_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_cadastrarActionPerformed
        String nome = this.JTF_nome.getText();  // Pegando o texto do JTextField de nome
        String codigo = this.JTF_codigo.getText();  // Pegando o texto do JTextField de código
        String quantidadeText = this.JTF_quantidade.getText();  // Pegando o texto do JTextField de quantidade

        // Verificando se os campos estão vazios
        if (nome.isEmpty() || codigo.isEmpty() || quantidadeText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, preencha todos os campos!", "Erro de Cadastro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double quantidade = Double.parseDouble(quantidadeText);  // Convertendo o texto de quantidade para double

            // Chamando o método de cadastro do controle de produto
            boolean produtoCadastrado = controleProduto.cadastrarProduto(nome, codigo, quantidade);

            if (produtoCadastrado) {
                JOptionPane.showMessageDialog(rootPane, "Produto cadastrado com sucesso!", "Cadastro de Produto", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Produto com o código " + codigo + " já existe!", "Erro de Cadastro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Tratando caso a conversão para double falhe
            JOptionPane.showMessageDialog(rootPane, "Por favor, insira um número válido para a quantidade.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JB_cadastrarActionPerformed

    private void JB_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_limparActionPerformed
        this.JTF_nome.setText(null);
        this.JTF_codigo.setText(null);
        this.JTF_quantidade.setText(null);
    }//GEN-LAST:event_JB_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroProduto dialog = new CadastroProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_cadastrar;
    private javax.swing.JButton JB_cancelar;
    private javax.swing.JButton JB_limpar;
    private javax.swing.JLabel JL_codigo;
    private javax.swing.JLabel JL_nome;
    private javax.swing.JLabel JL_quantidade;
    private javax.swing.JLabel JL_textoPrincipal;
    private javax.swing.JTextField JTF_codigo;
    private javax.swing.JTextField JTF_nome;
    private javax.swing.JTextField JTF_quantidade;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
