/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ControleProduto;
import javax.swing.JOptionPane;


/**
 *
 * @author pedromoreira
 */
public class RelatorioProdutos extends javax.swing.JDialog {

    ControleProduto controleProduto = new ControleProduto();
    
    public RelatorioProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
        public RelatorioProdutos(TelaPrincipal aThis, boolean rootPaneCheckingEnabled, ControleProduto controleProduto) {
        this.controleProduto = controleProduto;
        initComponents();
        this.mudarVisibilidadeItensPesquisa(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JP_relatorio = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_relatorio = new javax.swing.JTextArea();
        JP_opcoesRelatorio = new javax.swing.JPanel();
        JL_tipoRelatorio = new javax.swing.JLabel();
        JRB_todosProdutos = new javax.swing.JRadioButton();
        JRB_umProduto = new javax.swing.JRadioButton();
        JL_pesquisa = new javax.swing.JLabel();
        JTF_pesquisa = new javax.swing.JTextField();
        JB_pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JTA_relatorio.setEditable(false);
        JTA_relatorio.setColumns(20);
        JTA_relatorio.setRows(5);
        jScrollPane1.setViewportView(JTA_relatorio);

        javax.swing.GroupLayout JP_relatorioLayout = new javax.swing.GroupLayout(JP_relatorio);
        JP_relatorio.setLayout(JP_relatorioLayout);
        JP_relatorioLayout.setHorizontalGroup(
            JP_relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_relatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        JP_relatorioLayout.setVerticalGroup(
            JP_relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_relatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        JL_tipoRelatorio.setText("Tipo de relatório:");

        JRB_todosProdutos.setText("Todos os produtos");
        JRB_todosProdutos.setDoubleBuffered(true);
        JRB_todosProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_todosProdutosActionPerformed(evt);
            }
        });

        JRB_umProduto.setText("Um produto");
        JRB_umProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_umProdutoActionPerformed(evt);
            }
        });

        JL_pesquisa.setText("Pesquisa:");

        JB_pesquisar.setText("Pesquisar");
        JB_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP_opcoesRelatorioLayout = new javax.swing.GroupLayout(JP_opcoesRelatorio);
        JP_opcoesRelatorio.setLayout(JP_opcoesRelatorioLayout);
        JP_opcoesRelatorioLayout.setHorizontalGroup(
            JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JL_pesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JL_tipoRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                        .addComponent(JRB_todosProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JRB_umProduto))
                    .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                        .addComponent(JTF_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_pesquisar)))
                .addGap(38, 38, 38))
        );
        JP_opcoesRelatorioLayout.setVerticalGroup(
            JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_opcoesRelatorioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_tipoRelatorio)
                    .addComponent(JRB_todosProdutos)
                    .addComponent(JRB_umProduto))
                .addGap(18, 18, 18)
                .addGroup(JP_opcoesRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_pesquisa)
                    .addComponent(JTF_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_pesquisar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JP_opcoesRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JP_relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JP_opcoesRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JP_relatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JRB_todosProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_todosProdutosActionPerformed
        // TODO add your handling code here:
        JRB_umProduto.setSelected(false);
        this.mudarVisibilidadeItensPesquisa(false);
        this.JTA_relatorio.setText(controleProduto.getRelatorioTodosProdutos());
    }//GEN-LAST:event_JRB_todosProdutosActionPerformed

    private void JRB_umProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_umProdutoActionPerformed
        // TODO add your handling code here:
        JRB_todosProdutos.setSelected(false);
        this.mudarVisibilidadeItensPesquisa(true);
        this.JTA_relatorio.setText("");
    }//GEN-LAST:event_JRB_umProdutoActionPerformed

    private void JB_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_pesquisarActionPerformed
        // Obtém o código digitado no JTextField de pesquisa
        String codigoPesquisa = this.JTF_pesquisa.getText().trim();

        // Usa o método do controle para buscar o relatório do produto
        String relatorio = controleProduto.getRelatorioProduto(codigoPesquisa);

        if (relatorio != null) {
            // Exibe o relatório no JTextArea
            this.JTA_relatorio.setText(relatorio);
        } else {
            // Se não encontrou o produto, exibe uma mensagem de erro
            JOptionPane.showMessageDialog(rootPane, "Produto não encontrado com o código: " + codigoPesquisa, "Produto Não Encontrado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JB_pesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RelatorioProdutos dialog = new RelatorioProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void mudarVisibilidadeItensPesquisa(boolean b){
        this.JL_pesquisa.setVisible(b);
        this.JTF_pesquisa.setVisible(b);
        this.JB_pesquisar.setVisible(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_pesquisar;
    private javax.swing.JLabel JL_pesquisa;
    private javax.swing.JLabel JL_tipoRelatorio;
    private javax.swing.JPanel JP_opcoesRelatorio;
    private javax.swing.JPanel JP_relatorio;
    private javax.swing.JRadioButton JRB_todosProdutos;
    private javax.swing.JRadioButton JRB_umProduto;
    private javax.swing.JTextArea JTA_relatorio;
    private javax.swing.JTextField JTF_pesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
