/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ControleCliente;
import controller.ControleFornecedor;
import controller.ControleProduto;
import controller.ControleFuncionario;
/**
 *
 * @author pedromoreira
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ControleFuncionario controleFuncionario = new ControleFuncionario();
    ControleProduto controleProduto = new ControleProduto();
    ControleFornecedor controleFornecedor = new ControleFornecedor();
    ControleCliente controleCliente = new ControleCliente();
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_cadastro = new javax.swing.JMenu();
        JMI_cadastrarProduto = new javax.swing.JMenuItem();
        JMI_cadastrarFuncionario = new javax.swing.JMenuItem();
        JMI_cadastradarForncecedor = new javax.swing.JMenuItem();
        JMI_cadastrarCliente = new javax.swing.JMenuItem();
        JM_relatorio = new javax.swing.JMenu();
        JMI_relatorioProdutos = new javax.swing.JMenuItem();
        JMI_relatorioFuncionarios = new javax.swing.JMenuItem();
        JMI_relatorioFornecedores = new javax.swing.JMenuItem();
        JMI_relatorioClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        JM_cadastro.setText("Cadastro");

        JMI_cadastrarProduto.setText("Produto");
        JMI_cadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_cadastrarProdutoActionPerformed(evt);
            }
        });
        JM_cadastro.add(JMI_cadastrarProduto);

        JMI_cadastrarFuncionario.setText("Funcionário");
        JMI_cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_cadastrarFuncionarioActionPerformed(evt);
            }
        });
        JM_cadastro.add(JMI_cadastrarFuncionario);

        JMI_cadastradarForncecedor.setText("Fornecedor");
        JMI_cadastradarForncecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_cadastradarForncecedorActionPerformed(evt);
            }
        });
        JM_cadastro.add(JMI_cadastradarForncecedor);

        JMI_cadastrarCliente.setText("Cliente");
        JMI_cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_cadastrarClienteActionPerformed(evt);
            }
        });
        JM_cadastro.add(JMI_cadastrarCliente);

        jMenuBar1.add(JM_cadastro);

        JM_relatorio.setText("Relatórios");

        JMI_relatorioProdutos.setText("Produtos");
        JMI_relatorioProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_relatorioProdutosActionPerformed(evt);
            }
        });
        JM_relatorio.add(JMI_relatorioProdutos);

        JMI_relatorioFuncionarios.setText("Funcionários");
        JMI_relatorioFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_relatorioFuncionariosActionPerformed(evt);
            }
        });
        JM_relatorio.add(JMI_relatorioFuncionarios);

        JMI_relatorioFornecedores.setText("Fornecedores");
        JMI_relatorioFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_relatorioFornecedoresActionPerformed(evt);
            }
        });
        JM_relatorio.add(JMI_relatorioFornecedores);

        JMI_relatorioClientes.setText("Clientes");
        JMI_relatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_relatorioClientesActionPerformed(evt);
            }
        });
        JM_relatorio.add(JMI_relatorioClientes);

        jMenuBar1.add(JM_relatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_relatorioProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_relatorioProdutosActionPerformed
        new RelatorioProdutos(this, rootPaneCheckingEnabled, controleProduto).setVisible(true);
    }//GEN-LAST:event_JMI_relatorioProdutosActionPerformed

    private void JMI_relatorioFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_relatorioFuncionariosActionPerformed
        new RelatorioFuncionarios(this, rootPaneCheckingEnabled, controleFuncionario).setVisible(true);
    }//GEN-LAST:event_JMI_relatorioFuncionariosActionPerformed

    private void JMI_relatorioFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_relatorioFornecedoresActionPerformed
        new RelatorioFornecedores(this, rootPaneCheckingEnabled, controleFornecedor).setVisible(true);
    }//GEN-LAST:event_JMI_relatorioFornecedoresActionPerformed

    private void JMI_cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_cadastrarProdutoActionPerformed
        new CadastroProduto(this, rootPaneCheckingEnabled, controleProduto).setVisible(true);
    }//GEN-LAST:event_JMI_cadastrarProdutoActionPerformed

    private void JMI_cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_cadastrarFuncionarioActionPerformed
         new CadastroFuncionario(this, rootPaneCheckingEnabled, controleFuncionario).setVisible(true);
    }//GEN-LAST:event_JMI_cadastrarFuncionarioActionPerformed

    private void JMI_cadastradarForncecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_cadastradarForncecedorActionPerformed
        new CadastroFornecedor(this, rootPaneCheckingEnabled, controleFornecedor).setVisible(true);
    }//GEN-LAST:event_JMI_cadastradarForncecedorActionPerformed

    private void JMI_cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_cadastrarClienteActionPerformed
        new CadastroCliente(this, rootPaneCheckingEnabled, controleCliente).setVisible(true);
    }//GEN-LAST:event_JMI_cadastrarClienteActionPerformed

    private void JMI_relatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_relatorioClientesActionPerformed
        new RelatorioClientes(this, rootPaneCheckingEnabled, controleCliente).setVisible(true);
    }//GEN-LAST:event_JMI_relatorioClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMI_cadastradarForncecedor;
    private javax.swing.JMenuItem JMI_cadastrarCliente;
    private javax.swing.JMenuItem JMI_cadastrarFuncionario;
    private javax.swing.JMenuItem JMI_cadastrarProduto;
    private javax.swing.JMenuItem JMI_relatorioClientes;
    private javax.swing.JMenuItem JMI_relatorioFornecedores;
    private javax.swing.JMenuItem JMI_relatorioFuncionarios;
    private javax.swing.JMenuItem JMI_relatorioProdutos;
    private javax.swing.JMenu JM_cadastro;
    private javax.swing.JMenu JM_relatorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
